### Get all games
GET http://localhost:5236/games

### Find game by id
GET http://localhost:5236/games/7

### Create a new game
POST http://localhost:5236/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genre": "Sandbox",
  "price": 19.99,
  "releaseDate": "2011-11-18"
}